### ISSUE TITLE
Notes for Resque 2.0

### ISSUE THREAD

**Issue by ono** [ono/resque-cleaner#31]
Most code of this repo was written years ago and it made me cry when I read it again. I have been thinking of refactoring but probably it makes more sense to do that when Resque 2.0 is officially out (although I am not really sure about the schedule and scope...). I put some notes about things I want to fix here.
- Split lib/resque_cleaner into several files
- Rewrite server(sinatra) code and templates
- Rewrite tests
- Have a simpler README. Migrate information about the console to wiki.

**Comment by gerrywastaken** [comment]
:) I was glad to see that you had already created this issue. I have been looking for a version of resque-cleaner for the new version of Resque-web.

**Comment by ono** [comment]
@gerrywastaken I haven't tried new version of Resque-web by myself. Does resque-cleaner still make sense with it? I might talk to the maintainer and ask if there is a possibility to merge this plugin(rewritten version) into it.

**Comment by gerrywastaken** [comment]
@ono Absolutely. The new resque web doesn't group failures by class and time or have any filtering for the failed jobs. It really doesn't have any of the features resque-cleaner provides.

**Comment by lukeasrodgers** [comment]
FWIW I think it is unlikely that resque 2.0 will be released any time soon, if ever.
