### ISSUE TITLE
Form for cleaner_exec not aware of used regex filter

### ISSUE THREAD

**Issue by staszek-arsdata** [ono/resque-cleaner#36]
I'm using resque cleaner a lot. I've found an issue with regex filter and cleaner_exec. 
When trying to retry or clear only jobs matching the regex, the regex filter is not taken into filtering and all jobs are being processed (as there's no regex specified).

For example there are total 300 jobs of class Shops::Jobs::Parse and 250 jobs of the class Shops::Jobs::Parse	 and matching to some regex. Web UI shows 250 jobs matching the regex, but when checking 'select all 250 jobs' and doing 'Clear', all 300 Jobs are removed :( 

I've found the issue in the code. There's missing` input type="hidden" name="regex"` for the `cleaner_exec` form in the file `lib/resque_cleaner/server/views/cleaner_list.erb` I will try to fork and do a pull request.

**Comment by staszek-arsdata** [comment]
I was able to fix the issue and did a pull request. 

I'm using git a lot on private repos. But that's my first time contribution to  open-source and my first github pull request, so I hope I've done it in accepted OS and  'github' way :-)

**Comment by ono** [comment]
Nice one! Closing this as we take care of this in https://github.com/ono/resque-cleaner/pull/37
