### ISSUE TITLE
setup via resque web engine? 

### ISSUE THREAD

**Issue by chrishough** [ono/resque-cleaner#41]
When you are using the resque web engine:

```
  # Resque Engine
  mount ResqueWeb::Engine => 'resque' if AppSettings.settings[:mount_resque_web]
```

How do you set this up? I can add this to the readme too.

**Comment by ono** [comment]
I think that's something resque-web should cover and there is an information.

- https://github.com/resque/resque-web#plugins
- https://github.com/resque/resque-web/blob/master/PLUGINS.md

Please contact the maintainer of the plugin if that doesn't work. Let me know if it requires resque-cleaner to change something.

**Comment by chrishough** [comment]
Hmmm... Both resque web and resque server work nearly the same way.  They mount as engines.  Unless I am missing something this would a cleaner adjustment either to the readme or the way it is installed to have the nav show up in the UI.  Am I confused here?

**Comment by ono** [comment]
@chrishough Could you create a sample app which lets me see the issue and share it on github please?

**Comment by chrishough** [comment]
Will do. Give me a few days and I will post one up for you.

**Comment by stefanahman** [comment]
@chrishough ping! any progress?

**Comment by chrishough** [comment]
It has been a minute since trying to fix this. What we did to get around this was requiring resque-server.  Do you want me to try a different test?
